### ISSUE TITLE
Analytics page backend

### ISSUE THREAD

**Issue by Danieldv-s** [COS301-SE-2024/Open-Electricity-Market#221]
Analytics page
- [x] #227
  - [x] Display consumption Curve
  - [x] Display Production Curve
  - [x] #231
- [x] #232
  - [x] Average buy price
  - [x] Average sell price
  - [x] Minimum bought price
  - [x] Maximum sold price
  - [x] #233
  - [x] #234

**Comment by MasterJeddy** [comment]
Just to add so it is here it is cleaner if produced vs consumed is retrieved by market platform
